#!/usr/bin/env python3
import subprocess
import sys
import json
from pathlib import Path


def run_builder_with_inputs(inputs, cwd: Path):
    input_str = "\n".join(inputs) + "\n"
    proc = subprocess.run(
        [sys.executable, str(cwd / "config_builder.py")],
        input=input_str,
        text=True,
        capture_output=True,
        cwd=str(cwd),
        timeout=30,
    )
    return proc


def test_config_builder_generates_canonical_files(tmp_path):
    """Run the config builder non-interactively and assert files and contract."""
    repo_root = Path(__file__).resolve().parents[1]

    # Prepare inputs matching the interactive flow used previously
    test_inputs = [
        "y",  # Ready to begin
        "1",  # 1 middle layer
        "reformulator node",  # layer 1 node
        "1",  # middle layer node count
        "semantic node",  # middle node name
        "synthesis node",  # final node name
        # LLM config for reformulator node
        "1", "0.8", "2", "4096",
        # LLM config for semantic node
        "1", "0.8", "2", "4096",
        # LLM config for synthesis node
        "1", "0.6", "3", "4096",
        # Templates: epistemic tasks and expected outputs and a couple instructions
        "You are an epistemological reformulator",
        "reformulated_question",
        "Neutralize biases",
        "Prime for emplotment",
        "",
        "You are a semantic epistemologist analyzing meaning and intent",
        "semantic_analysis",
        "Analyze deeply",
        "Find patterns",
        "",
        "You are a master synthesizer that weaves ideas together",
        "comprehensive_synthesis",
        "Synthesize insights",
        "Create coherent narrative",
        "",
        "y",  # Save files
    ]

    # Run builder in repo root (it will create layer.json and template.json there)
    proc = run_builder_with_inputs(test_inputs, repo_root)
    assert proc.returncode == 0, f"Builder failed: {proc.stderr}\n{proc.stdout}"

    layer_file = repo_root / "layer.json"
    template_file = repo_root / "template.json"
    assert layer_file.exists(), "layer.json was not created"
    assert template_file.exists(), "template.json was not created"

    # Validate template.json canonical structure
    data = json.loads(template_file.read_text(encoding="utf-8"))
    assert "templates" in data and isinstance(data["templates"], dict)

    # Check each template has the canonical keys
    for tid, t in data["templates"].items():
        assert "template" in t, f"template key missing for {tid}"
        assert "input_context" in t, f"input_context missing for {tid}"
        assert "expected_output" in t, f"expected_output missing for {tid}"
        # First-layer template should use {query} as input_context
    # Find reformulator_node template (ID generated by builder)
    reform_id = "reformulator_node"
    if reform_id in data["templates"]:
        assert data["templates"][reform_id]["input_context"] == "{query}"

    # Cleanup created files (but leave backups alone)
    for p in [layer_file, template_file]:
        if p.exists():
            p.unlink()
import subprocess
import sys
from pathlib import Path


def test_config_builder_creates_files(tmp_path):
    # Prepare inputs similar to original test script
    test_inputs = [
        "y",  # Ready to begin
        "1",  # 1 middle layer
        "reformulator node",  # Node name for layer 1
        "1",  # 1 node in middle layer
        "semantic node",  # Node name for middle layer
        "synthesis node",  # Node name for final layer
        "1",  # Model choice for layer 1 node (openai/gpt-oss-20b)
        "0.8",  # Temperature for layer 1 node
        "2",  # Reasoning effort for layer 1 node (medium)
        "4096",  # Max tokens for layer 1 node
        "1",  # Model choice for middle layer node (openai/gpt-oss-20b)
        "0.8",  # Temperature for middle layer node
        "2",  # Reasoning effort for middle layer node (medium)
        "4096",  # Max tokens for middle layer node
        "1",  # Model choice for final layer node (openai/gpt-oss-20b)
        "0.6",  # Temperature for final layer node
        "3",  # Reasoning effort for final layer node (high)
        "4096",  # Max tokens for final layer node
        "You are an epistemological reformulator",  # Epistemic task for layer 1 node
        "reformulated_question",  # Expected output for layer 1 node
        "Neutralize biases",  # Instruction 1 for layer 1 node
        "Prime for emplotment",  # Instruction 2 for layer 1 node
        "",  # End instructions for layer 1 node
        "You are a semantic epistemologist analyzing meaning and intent",  # Epistemic task for middle layer node
        "semantic_analysis",  # Expected output for middle layer node
        "Analyze deeply",  # Instruction 1 for middle layer node
        "Find patterns",  # Instruction 2 for middle layer node
        "",  # End instructions for middle layer node
        "You are a master synthesizer that weaves ideas together",  # Epistemic task for final layer node
        "comprehensive_synthesis",  # Expected output for final layer node
        "Synthesize insights",  # Instruction 1 for final layer node
        "Create coherent narrative",  # Instruction 2 for final layer node
        "",  # End instructions for final layer node
        "y",  # Save files
    ]

    input_string = "\n".join(test_inputs) + "\n"

    # Run config_builder.py in the temporary directory
    proc = subprocess.run([
        sys.executable, str(Path.cwd() / "config_builder.py")
    ], input=input_string, text=True, capture_output=True, cwd=tmp_path)

    # Check that files were created
    layer_file = tmp_path / "layer.json"
    template_file = tmp_path / "template.json"

    assert proc.returncode == 0
    assert layer_file.exists(), "layer.json should be created"
    assert template_file.exists(), "template.json should be created"
